import { useMemo } from 'react';
import { ProcessedRequest } from '../lib/dataProcessing';
import { WARD_ORDER } from '../lib/constants';
import { useDashboard } from '../context/DashboardContext';

export interface FilterOption {
  label: string;
  value: string;
}

export interface FilterOptions {
  categories: FilterOption[];
  serviceTypes: FilterOption[];
  agencies: FilterOption[];
  wards: FilterOption[];
}

/** Derives filter dropdown options from loaded rows. */
export function useFilterOptions(rows: ProcessedRequest[] | undefined): FilterOptions {
  const { data } = useDashboard();
  // categoryMap comes from the manifest (generated by Python build); stable reference per load.
  const manifest = data?.manifest;

  return useMemo(() => {
    // Category ordering comes from the manifest's categoryMap (generated by Python build).
    const categoryMap = manifest?.categoryMap ?? {};

    if (!rows?.length) {
      return {
        categories: [],
        serviceTypes: [],
        agencies: [],
        wards: WARD_ORDER.map((w) => ({ label: w, value: w })),
      };
    }

    const serviceTypeCounts = new Map<string, number>();
    const agencies = new Set<string>();
    const categoriesFromData = new Set<string>();

    for (const r of rows) {
      serviceTypeCounts.set(
        r.SERVICECODEDESCRIPTION,
        (serviceTypeCounts.get(r.SERVICECODEDESCRIPTION) || 0) + 1,
      );
      categoriesFromData.add(r.category);
      if (r.ORGANIZATIONACRONYM) agencies.add(r.ORGANIZATIONACRONYM);
    }

    // Known categories from the manifest's authoritative map, then any unknowns from data.
    const knownCategories = new Set(Object.values(categoryMap));
    const allCategories = [
      ...Array.from(knownCategories).filter((c) => categoriesFromData.has(c)),
      ...Array.from(categoriesFromData).filter((c) => !knownCategories.has(c)),
    ]
      .sort((a, b) => a.localeCompare(b))
      .map((c) => ({ label: c, value: c }));

    return {
      categories: allCategories,
      serviceTypes: Array.from(serviceTypeCounts.entries())
        .map(([type, count]) => ({ label: `${type} (${count.toLocaleString()})`, value: type }))
        .sort((a, b) => a.label.localeCompare(b.label)),
      agencies: Array.from(agencies).sort().map((a) => ({ label: a, value: a })),
      wards: WARD_ORDER.map((w) => ({ label: w, value: w })),
    };
  }, [rows, manifest]);
}
